language: node_js
node_js:
  - "node"
cache: yarn
install: yarn
script:
  - yarn test
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then yarn appr; fi'
env:
  - STAGING_CHAT_ENDOINT="https://hsc-backend-staging.herokuapp.com"
  - PROD_CHAT_ENDPOINT="https://hsc-backend.herokuapp.com"
before_install:
  - |
      if [ "$TRAVIS_BRANCH" = "staging" ]; then
        for prefixed_envvar in ${!STAGING_*}; do
          eval export ${prefixed_envvar#STAGING_}="${!prefixed_envvar}"
        done
      elif [ "$TRAVIS_BRANCH" = "master" ]; then
        for prefixed_envvar in ${!PROD_*}; do
          eval export ${prefixed_envvar#PROD_}="${!prefixed_envvar}"
        done
      fi
